name: Deploy MyST site to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install MyST CLI
        run: |
          npm install -g mystmd
          myst --version

      - name: Build MyST site
        run: myst build --html

      - name: Add .nojekyll and CNAME
        run: |
          touch _build/html/.nojekyll
          echo "research.versioneer.at" > _build/html/CNAME

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _build/html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
